name: Hussain Fakhruddin
description: Blogging about tech stuff
meta_description: "Blogging about technology stuff"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: https://hussain.io/
domain_name: 'https://hussain.io'
permalink: '/:year/:month/:title'

# Details for the RSS feed generator
url:            'https://hussain.io'
author:         'Hussain Fakhruddin'
